name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install &  Build
      run: |
        cd news-on-earth
        yarn install
        yarn build

    # - name: Deploy to Cloudflare
    #   uses: cloudflare/wrangler-action@1.3.0
    #   with:
    #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    #     environment: 'production'

    - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: "cloudflare-pages-with-github-actions-prac"
          directory: ./dist
          